#!/bin/sh

per_thousand=${per_thousand:-10}
device=${device:-$(find /sys/class/backlight/ -name 'brightness' -printf "%h " 2>/dev/null)}
max_brightness=$(< $device/max_brightness)
step=$(( max_brigthness * per_thousand / 1000 )) 


case $1 in
  -) echo $(($(< $device/brightness) - $step)) >$bl_dev/brightness;;
  +) echo $(($(< $bl_dev/brightness) + $step)) >$bl_dev/brightness;;
esac
